program: train_wandb_log.py
entity: minhangxu1998-baylor-college-of-medicine
project: utr5__polysome__scratch__utr_bassetvl
method: bayes
metric:
  name: epoch_end_val_pearson_r2
  goal: maximize
parameters:
  data_module:
    value: UTR_Polysome_MPRA_DataModule
  datafile_path:
    value: /home/minhang/synBio_AL/opt_EU_learn_n_design/5utr_learn/GSM3130441_mcherry_1.csv
  sep:
    value: comma
  sequence_column:
    value: utr
  activity_columns:
    value: rl
  total_reads_column:
    value: total
  left_flank:
    value: ""
  right_flank:
    value: ""
  padded_seq_len:
    value: 50
  use_reverse_complements:
    value: False
  batch_size:
    distribution: categorical
    values: [128, 256, 512]
  author_style_split:
    value: True
  use_standard_scaler:
    value: True
  top_n:
    value: 180000
  test_n:
    value: 20000
  seed:
    value: 42

  model_module:
    value: UTR_BassetVL
  input_len:
    value: 50
  conv1_channels:
    distribution: int_uniform
    min: 80
    max: 200
  conv1_kernel_size:
    distribution: categorical
    values: [6, 8, 10]
  conv2_channels:
    distribution: int_uniform
    min: 80
    max: 200
  conv2_kernel_size:
    distribution: categorical
    values: [6, 8, 10]
  conv3_channels:
    distribution: int_uniform
    min: 80
    max: 200
  conv3_kernel_size:
    distribution: categorical
    values: [6, 8, 10]
  n_linear_layers:
    distribution: categorical
    values: [1, 2]
  linear_channels:
    distribution: int_uniform
    min: 40
    max: 128
  linear_activation:
    distribution: categorical
    values: [ReLU, LeakyReLU]
  linear_dropout_p:
    distribution: uniform
    min: 0.1
    max: 0.5
  n_outputs:
    value: 1
  use_batch_norm:
    value: True
  use_weight_norm:
    value: False
  loss_criterion:
    value: MSELoss

  graph_module:
    value: CNNBasicTraining
  optimizer:
    distribution: categorical
    values: [Adam, AdamW]
  lr:
    distribution: log_uniform_values
    min: 0.0001
    max: 0.01
  weight_decay:
    distribution: log_uniform_values
    min: 0.00001
    max: 0.001
  amsgrad:
    value: True
  beta1:
    distribution: uniform
    min: 0.8
    max: 0.95
  beta2:
    distribution: uniform
    min: 0.99
    max: 0.999
  checkpoint_monitor:
    value: epoch_end_val_pearson_r2
  stopping_mode:
    value: max
  stopping_patience:
    value: 40

  accelerator:
    value: gpu
  devices:
    value: 1
  min_epochs:
    value: 30
  max_epochs:
    value: 300
  precision:
    value: 16
  default_root_dir:
    value: /home/minhang/synBio_AL/boda2_EU/src/learn/outputs/utr5/polysome/utr_bassetvl/bayes_mcherry_1
  artifact_path:
    value: /home/minhang/synBio_AL/boda2_EU/src/learn/local_artifacts/utr5/polysome/utr_bassetvl/bayes_mcherry_1
  tolerate_unknown_args:
    value: False

  logger_type:
    value: wandb
  logger_project:
    value: utr5__polysome__scratch__utr_bassetvl
  run_name:
    value: utr5_polysome__mcherry_1__hpo_{runid}
