program: train_wandb_log.py
method: bayes
metric:
  name: epoch_end_val_pearson_r2
  goal: maximize
entity: minhangxu1998-baylor-college-of-medicine
project: enhancer__bashor_in_house__scratch_basic__bassetvl_vs_resnet1d
parameters:
  data_module:
    value: Lib1EnhancerDataModule
  model_module:
    values: [BassetVL, ResNet1DRegressor]
  n_outputs:
    value: 1
  loss_criterion:
    value: MSELoss
  graph_module:
    value: CNNBasicTraining
  logger_project:
    value: enhancer__bashor_in_house__scratch_basic__bassetvl_vs_resnet1d
  run_name:
    value: lib1_scratch_basic_{runid}
  artifact_path:
    value: /home/minhang/synBio_AL/boda2_EU/src/learn/local_artifacts/enhancer/bashor_in_house/lib1_scratch_basic
  default_root_dir:
    value: /home/minhang/synBio_AL/boda2_EU/src/learn/outputs/enhancer/bashor_in_house/lib1_scratch_basic
  datafile_path:
    value: /home/minhang/synBio_AL/opt_EU_learn_n_design/MattLee_lib1/enhancers/20251218_np_fastq1_500000NPreads_enh_variants_bc_sum_avg_expression.txt
  sequence_column:
    value: Enhancers
  target_column:
    value: RNA_DNA_Ratio_log10_scaled
  barcode_column:
    value: n_barcodes
  test_min_barcodes:
    value: 4
  #train_min_barcodes:
  #  values: [1, 2, 3]
  val_frac_within_hq:
    value: 0.25
  test_frac_within_hq:
    value: 0.25
  #train_size_frac:
  #  values: [0.1, 0.2, 0.35, 0.5, 0.75, 1.0]
  train_sampling_mode:
    value: hq_first
  use_reverse_complements:
    values: [true, false]
  barcode_weighting:
    value: false
  #batch_size:
  #   values: [64, 128]
  optimizer:
    value: AdamW
  scheduler:
    value: ReduceLROnPlateau
  scheduler_monitor:
    value: step_valid_loss
  scheduler_interval:
    value: epoch
  lr:
    distribution: log_uniform_values
    min: 1e-5
    max: 5e-3
  weight_decay:
    distribution: log_uniform_values
    min: 1e-6
    max: 1e-2
  max_epochs:
    value: 50
  checkpoint_monitor:
    value: epoch_end_val_pearson_r2
  stopping_mode:
    value: max
  stopping_patience:
    value: 15
  accelerator:
    value: gpu
  devices:
    value: 1
