program: train_wandb_log.py
entity: minhangxu1998-baylor-college-of-medicine
project: promoter__bashor_in_house__lib1_allvalid__scratch__promoter_bassetvl
method: bayes
metric:
  name: val_pearson
  goal: maximize
parameters:
  epoch_eval_splits:
    value: [train, val, test]
  data_module:
    value: Lib1PromoterDataModule
  datafile_path:
    value: /home/minhang/synBio_AL/boda2_EU/src/learn/derived_data/promoter/bashor_in_house/lib1_promoter_allvalid_fastqs1_5__learn_ready.tsv
  sep:
    value: tab
  sequence_column:
    value: Promoter
  target_column:
    value: log2_RNA_DNA
  barcode_column:
    value: n_barcodes
  padded_seq_len:
    value: 51
  padding_mode:
    value: neutral
  neutral_pad_char:
    value: N
  normalize:
    value: true
  test_min_barcodes:
    value: 8
  train_min_barcodes:
    value: 1
  val_frac_within_hq:
    value: 0.1295
  test_frac_within_hq:
    value: 0.1295
  val_size_within_hq:
    value: 250
  test_size_within_hq:
    value: 250
  train_size_frac:
    value: 1.0
  train_sampling_mode:
    value: random
  split_seed:
    value: 101
  use_reverse_complements:
    distribution: categorical
    values: [false, true]
  barcode_weighting:
    value: false

  graph_module:
    value: CNNBasicTraining
  model_module:
    value: PromoterBassetVL
  input_len:
    value: 51
  n_outputs:
    value: 1
  output_names:
    value: [log2_RNA_DNA]
  log_per_output_metric_details:
    value: false
  log_legacy_metric_aliases:
    value: false

  conv1_channels:
    distribution: int_uniform
    min: 32
    max: 128
  conv1_kernel_size:
    distribution: categorical
    values: [5, 7, 9, 11]
  conv2_channels:
    distribution: int_uniform
    min: 32
    max: 128
  conv2_kernel_size:
    distribution: categorical
    values: [3, 5, 7, 9]
  conv3_channels:
    distribution: int_uniform
    min: 24
    max: 96
  conv3_kernel_size:
    distribution: categorical
    values: [3, 5, 7]
  adaptive_pool_output_size:
    distribution: categorical
    values: [4, 6, 8, 12]
  n_linear_layers:
    distribution: categorical
    values: [1, 2]
  linear_channels:
    distribution: int_uniform
    min: 32
    max: 192
  linear_activation:
    distribution: categorical
    values: [ReLU, LeakyReLU, ELU]
  linear_dropout_p:
    distribution: uniform
    min: 0.2
    max: 0.65
  use_batch_norm:
    distribution: categorical
    values: [true, false]
  use_weight_norm:
    value: false
  loss_criterion:
    value: MSELoss
  reduction:
    value: mean

  optimizer:
    value: AdamW
  lr:
    distribution: log_uniform_values
    min: 0.00001
    max: 0.001
  weight_decay:
    distribution: log_uniform_values
    min: 0.00001
    max: 0.01
  amsgrad:
    distribution: categorical
    values: [true, false]
  beta1:
    distribution: uniform
    min: 0.84
    max: 0.96
  beta2:
    distribution: uniform
    min: 0.985
    max: 0.999
  scheduler:
    value: "None"
  scheduler_interval:
    value: step

  batch_size:
    distribution: categorical
    values: [64, 128, 256]
  num_workers:
    value: 8
  max_epochs:
    value: 180
  min_epochs:
    value: 20
  stopping_patience:
    value: 30
  stopping_mode:
    value: max
  checkpoint_monitor:
    value: val_pearson
  accelerator:
    value: gpu
  devices:
    value: 1
  precision:
    value: 32
  logger_type:
    value: wandb
  logger_project:
    value: promoter__bashor_in_house__lib1_allvalid__scratch__promoter_bassetvl
  run_name:
    value: lib1_promoter_promoter_bassetvl_scratch_{runid}
  artifact_path:
    value: /home/minhang/synBio_AL/boda2_EU/src/learn/local_artifacts/promoter/bashor_in_house/lib1_allvalid/promoter_bassetvl/scratch_bayes
  best_checkpoint_dir:
    value: /home/minhang/synBio_AL/boda2_EU/src/learn/outputs/hpo_runs/by_project/promoter__bashor_in_house__lib1_allvalid__scratch__promoter_bassetvl/best_checkpoint_model
  default_root_dir:
    value: /home/minhang/synBio_AL/boda2_EU/src/learn/outputs/promoter/bashor_in_house/lib1_allvalid/promoter_bassetvl/scratch_bayes
