#!/bin/bash
set -euo pipefail

# Global-queue launcher for the Lib1 no-RC outer-split-seed prior-informed HPO
# manifest generated by ../generate_lib1_outer_seed_prior_hpo_manifest.py.
#
# Pilot dry run:
#   cd /home/minhang/synBio_AL/boda2_EU
#   python src/learn/generate_lib1_outer_seed_prior_hpo_manifest.py
#   DRY_RUN=1 GPU_LIST="0" PARTS="promoter" MAX_CONFIGS_PER_PART=2 \
#     SPLIT_SEEDS="101 202" \
#     bash src/learn/launch/lib1_inhouse_outer_seed_prior_orchestrator.sh

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LEARN_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
source "${SCRIPT_DIR}/_wandb_helpers.sh"

MANIFEST_TAG="${MANIFEST_TAG:-lib1_outer_seed_prior_no_rc_june2026}"
MANIFEST_JSONL="${MANIFEST_JSONL:-${LEARN_DIR}/outputs/hpo_manifests/${MANIFEST_TAG}__run_manifest.jsonl}"
RUNS_CSV="${RUNS_CSV:-${LEARN_DIR}/run_registry/runs.csv}"
STATUS_DIR="${STATUS_DIR:-${LEARN_DIR}/outputs/hpo_runs/status/${MANIFEST_TAG}}"

DRY_RUN="${DRY_RUN:-0}"
SKIP_COMPLETED="${SKIP_COMPLETED:-1}"
PARTS="${PARTS:-}"
ROW_RANGE="${ROW_RANGE:-}"
ROW_START="${ROW_START:-}"
ROW_END="${ROW_END:-}"
MAX_ROWS="${MAX_ROWS:-}"
SPLIT_SEEDS="${SPLIT_SEEDS:-}"
CONFIG_IDS="${CONFIG_IDS:-}"
MAX_CONFIGS_PER_PART="${MAX_CONFIGS_PER_PART:-}"
LAUNCH_NOTES="${LAUNCH_NOTES:-${MANIFEST_TAG}}"

if [[ ! -f "${MANIFEST_JSONL}" ]]; then
  echo "ERROR: manifest JSONL not found: ${MANIFEST_JSONL}" >&2
  echo "Generate it first with:" >&2
  echo "  cd ${LEARN_DIR}" >&2
  echo "  python generate_lib1_outer_seed_prior_hpo_manifest.py" >&2
  exit 1
fi

if [[ -n "${GPU_LIST:-}" ]]; then
  read -r -a GPU_ARRAY <<< "${GPU_LIST}"
elif [[ "${DRY_RUN}" == "1" ]]; then
  GPU_ARRAY=(0)
else
  mapfile -t GPU_ARRAY < <(detect_idle_gpus)
fi

if [[ ${#GPU_ARRAY[@]} -eq 0 ]]; then
  echo "ERROR: no GPUs selected. Set GPU_LIST or free GPUs for auto-detection." >&2
  exit 1
fi

export STATUS_DIR
export PARTS ROW_RANGE ROW_START ROW_END MAX_ROWS SPLIT_SEEDS CONFIG_IDS MAX_CONFIGS_PER_PART
export SKIP_COMPLETED

manifest_helper() {
  local action="$1"
  shift
  python - "${action}" "${MANIFEST_JSONL}" "${RUNS_CSV}" "$@" <<'PY'
import csv
import json
import os
import sys
from pathlib import Path


action = sys.argv[1]
manifest_path = Path(sys.argv[2])
runs_csv = Path(sys.argv[3])
extra = sys.argv[4:]
status_dir = Path(os.environ.get("STATUS_DIR", ""))


def tokens(value):
    if not value:
        return []
    normalized = value.replace(",", " ").replace(";", " ")
    return [item.strip() for item in normalized.split() if item.strip()]


def norm_part(value):
    key = str(value).strip().lower().replace("-", "").replace("_", "")
    aliases = {
        "promoter": "Promoter",
        "intron": "Intron",
        "introns": "Intron",
        "3utr": "3UTR",
        "utr3": "3UTR",
        "threeprime": "3UTR",
        "threeprimeutr": "3UTR",
        "5utr": "5UTR",
        "utr5": "5UTR",
        "fiveprime": "5UTR",
        "fiveprimeutr": "5UTR",
    }
    return aliases.get(key, value)


def load_rows():
    rows = []
    with manifest_path.open() as fh:
        for line in fh:
            line = line.strip()
            if line:
                rows.append(json.loads(line))
    return rows


def parse_range():
    start = os.environ.get("ROW_START", "").strip()
    end = os.environ.get("ROW_END", "").strip()
    row_range = os.environ.get("ROW_RANGE", "").strip()
    if row_range and (not start and not end):
        sep = "-" if "-" in row_range else ":"
        if sep in row_range:
            left, right = row_range.split(sep, 1)
            start = left.strip()
            end = right.strip()
    start_i = int(start) if start else None
    end_i = int(end) if end else None
    return start_i, end_i


def row_completed(row):
    planned = str(row.get("planned_run_name", ""))
    manifest_row = str(row.get("manifest_row", ""))
    done_file = status_dir / "done" / ("row_{}.done".format(manifest_row))
    if done_file.exists():
        return True
    if not runs_csv.exists() or not planned:
        return False
    try:
        with runs_csv.open(newline="") as fh:
            reader = csv.DictReader(fh)
            for rec in reader:
                if str(rec.get("status", "")) != "completed":
                    continue
                run_name = str(rec.get("run_name", ""))
                if run_name == planned or run_name.startswith(planned + "_"):
                    return True
    except Exception:
        return False
    return False


def selected_rows():
    rows = load_rows()
    selected_parts = {norm_part(item) for item in tokens(os.environ.get("PARTS", ""))}
    selected_config_ids = set(tokens(os.environ.get("CONFIG_IDS", "")))
    selected_split_seeds = {int(item) for item in tokens(os.environ.get("SPLIT_SEEDS", ""))}
    row_start, row_end = parse_range()

    filtered = []
    for row in rows:
        manifest_row = int(row["manifest_row"])
        if row_start is not None and manifest_row < row_start:
            continue
        if row_end is not None and manifest_row > row_end:
            continue
        if selected_parts and norm_part(row.get("part")) not in selected_parts:
            continue
        if selected_config_ids and str(row.get("config_id")) not in selected_config_ids:
            continue
        if selected_split_seeds and int(row.get("split_seed")) not in selected_split_seeds:
            continue
        filtered.append(row)

    max_configs = os.environ.get("MAX_CONFIGS_PER_PART", "").strip()
    if max_configs:
        max_configs_i = int(max_configs)
        allowed = {}
        seen = {}
        for row in filtered:
            part = row.get("part")
            config_id = row.get("config_id")
            seen.setdefault(part, [])
            if config_id not in seen[part]:
                seen[part].append(config_id)
            if len(seen[part]) <= max_configs_i:
                allowed.setdefault(part, set()).add(config_id)
        filtered = [row for row in filtered if row.get("config_id") in allowed.get(row.get("part"), set())]

    if os.environ.get("SKIP_COMPLETED", "1") == "1":
        filtered = [row for row in filtered if not row_completed(row)]

    max_rows = os.environ.get("MAX_ROWS", "").strip()
    if max_rows:
        filtered = filtered[: int(max_rows)]
    return filtered


def row_by_number(number):
    wanted = int(number)
    for row in load_rows():
        if int(row.get("manifest_row")) == wanted:
            return row
    raise SystemExit("No manifest row {}".format(number))


if action == "list":
    for row in selected_rows():
        print(row["manifest_row"])
elif action == "dry":
    fields = [
        "manifest_row",
        "part",
        "config_id",
        "split_seed",
        "planned_run_name",
        "wandb_entity",
        "logger_project",
        "task_family",
        "target_family",
        "comparison_group",
        "train_command",
    ]
    for row in selected_rows():
        print("\t".join(str(row.get(field, "")) for field in fields))
elif action == "command":
    print(row_by_number(extra[0]).get("train_command", ""))
elif action == "field":
    row = row_by_number(extra[0])
    print(row.get(extra[1], ""))
elif action == "completed":
    sys.exit(0 if row_completed(row_by_number(extra[0])) else 1)
else:
    raise SystemExit("Unknown action: {}".format(action))
PY
}

echo "Lib1 outer-seed prior-informed HPO orchestrator"
echo "MANIFEST_JSONL=${MANIFEST_JSONL}"
echo "RUNS_CSV=${RUNS_CSV}"
echo "STATUS_DIR=${STATUS_DIR}"
echo "GPU_LIST=${GPU_ARRAY[*]}"
echo "DRY_RUN=${DRY_RUN}"
echo "SKIP_COMPLETED=${SKIP_COMPLETED}"
echo "PARTS=${PARTS:-<all>}"
echo "ROW_RANGE=${ROW_RANGE:-<none>}"
echo "ROW_START=${ROW_START:-<none>}"
echo "ROW_END=${ROW_END:-<none>}"
echo "MAX_ROWS=${MAX_ROWS:-<none>}"
echo "MAX_CONFIGS_PER_PART=${MAX_CONFIGS_PER_PART:-<none>}"
echo "SPLIT_SEEDS=${SPLIT_SEEDS:-<all>}"
echo "CONFIG_IDS=${CONFIG_IDS:-<all>}"

if [[ "${DRY_RUN}" == "1" ]]; then
  echo
  echo "DRY_RUN=1: commands that would be executed"
  row_count=0
  gpu_count="${#GPU_ARRAY[@]}"
  while IFS=$'\t' read -r manifest_row part config_id split_seed planned_run_name wandb_entity logger_project task_family target_family comparison_group train_command; do
    gpu_id="${GPU_ARRAY[$((row_count % gpu_count))]}"
    row_count=$((row_count + 1))
    echo
    echo "Row ${manifest_row}: part=${part} config_id=${config_id} split_seed=${split_seed} gpu=${gpu_id}"
    echo "Run name: ${planned_run_name}"
    echo "(cd ${LEARN_DIR} && \\"
    echo "  CUDA_VISIBLE_DEVICES=${gpu_id} WANDB_ENTITY=${wandb_entity} \\"
    echo "  BODA_CONFIG_PATH=${MANIFEST_JSONL} \\"
    echo "  BODA_TASK_FAMILY=${task_family} BODA_TARGET_FAMILY=${target_family} \\"
    echo "  BODA_COMPARISON_GROUP=${comparison_group} \\"
    echo "  BODA_LAUNCH_SCRIPT=launch/lib1_inhouse_outer_seed_prior_orchestrator.sh \\"
    echo "  BODA_WANDB_ENTITY=${wandb_entity} BODA_WANDB_PROJECT=${logger_project} \\"
    echo "  BODA_RUNS_CSV=${RUNS_CSV} BODA_LAUNCH_NOTES=${LAUNCH_NOTES} \\"
    echo "  bash -lc $(printf '%q' "${train_command}"))"
  done < <(manifest_helper dry)
  echo
  echo "DRY_RUN selected rows: ${row_count}"
  exit 0
fi

mapfile -t QUEUE_ROWS < <(manifest_helper list)
if [[ ${#QUEUE_ROWS[@]} -eq 0 ]]; then
  echo
  echo "No manifest rows selected after filters/completion checks."
  exit 0
fi

LAUNCH_ID="$(date +%Y%m%d_%H%M%S)_$$"
CLAIM_DIR="${STATUS_DIR}/claims/${LAUNCH_ID}"
DONE_DIR="${STATUS_DIR}/done"
FAIL_DIR="${STATUS_DIR}/failures/${LAUNCH_ID}"
LOG_DIR="${STATUS_DIR}/logs/${LAUNCH_ID}"
mkdir -p "${CLAIM_DIR}" "${DONE_DIR}" "${FAIL_DIR}" "${LOG_DIR}"

run_manifest_row() {
  local gpu_id="$1"
  local worker_id="$2"
  local manifest_row="$3"
  local train_command planned_run_name wandb_entity logger_project task_family target_family comparison_group
  local row_log fail_file

  train_command="$(manifest_helper command "${manifest_row}")"
  planned_run_name="$(manifest_helper field "${manifest_row}" planned_run_name)"
  wandb_entity="$(manifest_helper field "${manifest_row}" wandb_entity)"
  logger_project="$(manifest_helper field "${manifest_row}" logger_project)"
  task_family="$(manifest_helper field "${manifest_row}" task_family)"
  target_family="$(manifest_helper field "${manifest_row}" target_family)"
  comparison_group="$(manifest_helper field "${manifest_row}" comparison_group)"
  row_log="${LOG_DIR}/row_${manifest_row}.log"
  fail_file="${FAIL_DIR}/row_${manifest_row}.fail"

  echo "Worker ${worker_id} GPU ${gpu_id}: starting row ${manifest_row} (${planned_run_name})"
  if (
    cd "${LEARN_DIR}"
    CUDA_VISIBLE_DEVICES="${gpu_id}" \
    WANDB_ENTITY="${wandb_entity}" \
    BODA_CONFIG_PATH="${MANIFEST_JSONL}" \
    BODA_TASK_FAMILY="${task_family}" \
    BODA_TARGET_FAMILY="${target_family}" \
    BODA_COMPARISON_GROUP="${comparison_group}" \
    BODA_LAUNCH_SCRIPT="launch/lib1_inhouse_outer_seed_prior_orchestrator.sh" \
    BODA_SWEEP_PATH="" \
    BODA_SWEEP_ID="" \
    BODA_WANDB_ENTITY="${wandb_entity}" \
    BODA_WANDB_PROJECT="${logger_project}" \
    BODA_RUNS_CSV="${RUNS_CSV}" \
    BODA_LAUNCH_NOTES="${LAUNCH_NOTES}" \
    bash -lc "${train_command}"
  ) >"${row_log}" 2>&1; then
    {
      echo "completed_at=$(date -Iseconds)"
      echo "manifest_row=${manifest_row}"
      echo "planned_run_name=${planned_run_name}"
      echo "log=${row_log}"
    } > "${DONE_DIR}/row_${manifest_row}.done"
    echo "Worker ${worker_id} GPU ${gpu_id}: completed row ${manifest_row}"
    return 0
  else
    local status=$?
    {
      echo "failed_at=$(date -Iseconds)"
      echo "manifest_row=${manifest_row}"
      echo "planned_run_name=${planned_run_name}"
      echo "status=${status}"
      echo "log=${row_log}"
    } > "${fail_file}"
    echo "Worker ${worker_id} GPU ${gpu_id}: FAILED row ${manifest_row}; see ${row_log}" >&2
    return "${status}"
  fi
}

worker_loop() {
  local gpu_id="$1"
  local worker_id="$2"
  local manifest_row claim_path
  while true; do
    local claimed=""
    for manifest_row in "${QUEUE_ROWS[@]}"; do
      if [[ "${SKIP_COMPLETED}" == "1" ]] && manifest_helper completed "${manifest_row}"; then
        continue
      fi
      claim_path="${CLAIM_DIR}/row_${manifest_row}.claim"
      if mkdir "${claim_path}" 2>/dev/null; then
        claimed="${manifest_row}"
        break
      fi
    done
    if [[ -z "${claimed}" ]]; then
      echo "Worker ${worker_id} GPU ${gpu_id}: queue exhausted"
      return 0
    fi
    run_manifest_row "${gpu_id}" "${worker_id}" "${claimed}" || return $?
  done
}

echo
echo "Selected manifest rows: ${#QUEUE_ROWS[@]}"
echo "Starting ${#GPU_ARRAY[@]} worker(s)"

pids=()
for idx in "${!GPU_ARRAY[@]}"; do
  worker_loop "${GPU_ARRAY[idx]}" "$((idx + 1))" &
  pids+=("$!")
  sleep 1
done

status=0
for pid in "${pids[@]}"; do
  if ! wait "${pid}"; then
    status=1
  fi
done

if compgen -G "${FAIL_DIR}/row_*.fail" >/dev/null; then
  status=1
fi

if [[ "${status}" -eq 0 ]]; then
  echo
  echo "All selected manifest rows completed or were already skipped."
else
  echo
  echo "One or more manifest rows failed. Failure markers: ${FAIL_DIR}" >&2
fi
exit "${status}"
